version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./src/:/app
      - /etc/letsencrypt/live/feles-omen-desk.sfc.wide.ad.jp/fullchain.pem:/etc/ssl/notebook/notebook.pem:ro
      - /etc/letsencrypt/live/feles-omen-desk.sfc.wide.ad.jp/privkey.pem:/etc/ssl/notebook/notebook-key.pem:ro
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "vowkub-sajkyn-ribMi5"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

